export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const RESET_TEMP_PASSWORD = 'RESET_TEMP_PASSWORD';
export const RESET_TEMP_PASSWORD_SUCCESS = 'RESET_TEMP_PASSWORD_SUCCESS';
export const RESET_TEMP_PASSWORD_ERROR = 'RESET_TEMP_PASSWORD_ERROR';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR';

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_LOGGED_USER_SUCCESS = 'GET_LOGGED_USER_SUCCESS';
export const GET_LOGGED_USER_ERROR = 'GET_LOGGED_USER_ERROR';


export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

export const FACEBOOK_SIGNUP = 'FACEBOOK_SIGNUP';
export const FACEBOOK_SIGNUP_SUCCESS = 'FACEBOOK_SIGNUP_SUCCESS';
export const FACEBOOK_SIGNUP_ERROR = 'FACEBOOK_SIGNUP_ERROR';

export const APPLE_SIGNUP = 'APPLE_SIGNUP';
export const APPLE_SIGNUP_SUCCESS = 'APPLE_SIGNUP_SUCCESS';
export const APPLE_SIGNUP_ERROR = 'APPLE_SIGNUP_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const UPDATE_NOTIFICATION_IN_USER = 'UPDATE_NOTIFICATION_IN_USER';

export const GET_ALL_TOURNAMENTS = 'GET_ALL_TOURNAMENTS';
export const GET_ALL_TOURNAMENTS_SUCCESS = 'GET_ALL_TOURNAMENTS_SUCCESS';
export const GET_ALL_TOURNAMENTS_ERROR = 'GET_ALL_TOURNAMENTS_ERROR';

export const GET_TOURNAMENT_BY_ID = 'GET_TOURNAMENT_BY_ID';
export const GET_TOURNAMENT_BY_ID_SUCCESS = 'GET_TOURNAMENT_BY_ID_SUCCESS';
export const GET_TOURNAMENT_BY_ID_ERROR = 'GET_TOURNAMENT_BY_ID_ERROR';

export const GET_TOURNAMENT_BY_RANGE = 'GET_TOURNAMENT_BY_RANGE';
export const GET_TOURNAMENT_BY_RANGE_SUCCESS = 'GET_TOURNAMENT_BY_RANGE_SUCCESS';
export const GET_TOURNAMENT_BY_RANGE_ERROR = 'GET_TOURNAMENT_BY_RANGE_ERROR';

export const SET_TOURNAMENT = 'SET_TOURNAMENT';
export const SET_ROUND = 'SET_ROUND';

export const GET_ALL_GOLFERS = 'GET_ALL_GOLFERS';
export const GET_ALL_GOLFERS_SUCCESS = 'GET_ALL_GOLFERS_SUCCESS';
export const GET_ALL_GOLFERS_ERROR = 'GET_ALL_GOLFERS_ERROR';

export const GET_GOLFER = 'GET_GOLFER';
export const GET_GOLFER_SUCCESS = 'GET_GOLFER_SUCCESS';
export const GET_GOLFER_ERROR = 'GET_GOLFER_ERROR';

export const CREATE_RABBIT_CARD = 'CREATE_RABBIT_CARD';
export const CREATE_RABBIT_CARD_SUCCESS = 'CREATE_RABBIT_CARD_SUCCESS';
export const CREATE_RABBIT_CARD_ERROR = 'CREATE_RABBIT_CARD_ERROR';

export const GET_RABBIT_CARDS = 'GET_RABBIT_CARDS';
export const GET_RABBIT_CARDS_SUCCESS = 'GET_RABBIT_CARDS_SUCCESS';
export const GET_RABBIT_CARDS_ERROR = 'GET_RABBIT_CARDS_ERROR';

export const DELETE_RABBIT_CARD = 'DELETE_RABBIT_CARD';
export const DELETE_RABBIT_CARD_SUCCESS = 'DELETE_RABBIT_CARD_SUCCESS';
export const DELETE_RABBIT_CARD_ERROR = 'DELETE_RABBIT_CARD_ERROR';

export const GET_RABBIT_CARD_CHOICE = 'GET_RABBIT_CARD_CHOICE';
export const GET_RABBIT_CARD_CHOICE_SUCCESS = 'GET_RABBIT_CARD_CHOICE_SUCCESS';
export const GET_RABBIT_CARD_CHOICE_ERROR = 'GET_RABBIT_CARD_CHOICE_ERROR';

export const GET_GROUPINGS_PAR3S = 'GET_GROUPINGS_PAR3S';
export const GET_GROUPINGS_PAR3S_SUCCESS = 'GET_GROUPINGS_PAR3S_SUCCESS';
export const GET_GROUPINGS_PAR3S_ERROR = 'GET_GROUPINGS_PAR3S_ERROR';

export const GET_HOLE_GOLFERS = 'GET_HOLE_GOLFERS';
export const GET_HOLE_GOLFERS_SUCCESS = 'GET_HOLE_GOLFERS_SUCCESS';
export const GET_HOLE_GOLFERS_ERROR = 'GET_HOLE_GOLFERS_ERROR';

export const USER_CTTP_PICK = 'USER_CTTP_PICK';
export const USER_CTTP_PICK_SUCCESS = 'USER_CTTP_PICK_SUCCESS';
export const USER_CTTP_PICK_ERROR = 'USER_CTTP_PICK_ERROR';

export const SET_TAB = 'SET_TAB';


export const GET_USERRANKING = 'GET_USERRANKING';
export const GET_ALL_USERRANKING_SUCCESS = 'GET_ALL_USERRANKING_SUCCESS';
export const GET_ALL_USERRANKING_ERROR = 'GET_ALL_USERRANKING_ERROR';

export const GET_OVERALLRANKING = 'GET_OVERALLRANKING';
export const GET_OVERALLRANKING_SUCCESS = 'GET_OVERALLRANKING_SUCCESS';
export const GET_OVERALLRANKING_ERROR = 'GET_OVERALLRANKING_ERROR';

export const CREATE_TIEBRESKER = 'CREATE_TIEBRESKER';
export const CREATE_TIEBRESKER_SUCCESS = 'CREATE_TIEBRESKER_SUCCESS';
export const CREATE_TIEBRESKER_ERROR = 'CREATE_TIEBRESKER_ERROR';

export const TOKEN_CODE = 'TOKEN_CODE';
export const TOKEN_CODE_SUCCESS = 'TOKEN_CODE_SUCCESS';
export const TOKEN_CODE_ERROR = 'TOKEN_CODE_ERROR';

export const MYRABBITPURSE = 'MYRABBITPURSE';
export const MYRABBITPURSE_SUCCESS = 'MYRABBITPURSE_SUCCESS';
export const MYRABBITPURSE_ERROR = 'MYRABBITPURSE_ERROR';